
name: Active Mandarin course

tagline: Belajar bahasa mandarin jauh lebih mudah dengan activemandarin.id. yuk join sekarang dengan klik tombol di bawah ini


Image_URL: https://activemandarin.id/wp-content/uploads/2022/11/WhatsApp-Image-2022-11-10-at-09.29.12.jpg

Cover_Image: https://activemandarin.id/links/bg.jpg

# SOCIAL MEDIA
links:  

  - Name: Website
    URL: https://activemandarin.id
    Icon-Class: fa fa-globe
    Color: '#ffb142'
    Text_Color: '#ffffff'

    #Free trial
  - Name: Gabung Free Trial
    URL: https://t.me/activemandarin
    Username: 
    Color: '#1DA1F2'
    Icon-Class: fab fa-telegram-plane

    #Collab dengan PPIDK
  - Name: PPIDK X Active Mandarin
    URL: https://ppidk.activemandarin.id
    Color: '#ffb142'
    Icon-Class: fa-handshake

    # YOUTUBE
#  - Name: YouTube
 #   URL: https://www.youtube.com/channel
 #   Username: UCS3zvA_2r1iGT7MB3NVCGAw
 #   Color: '#ff0000'
 #   Icon-Class: fab fa-youtube
# instagram

  - Name: Instagram
    URL: https://www.instagram.com
    Username: activemandarin.id
    Color: '#c32aa3'
    Icon-Class: fab fa-instagram
# facebook
  - Name: Facebook
    URL: https://www.facebook.com
    Username: activemandarinindonesia
    Color: '#3b5998'
    Icon-Class: fab fa-facebook-f

#tiktok
  - Name: Tiktok
    URL: https://tiktok.com/@activemandarin
    Icon-Class: fab fa-tiktok
    Color: '#FE2C55'
    Text_Color: '#ffffff'

    # EMAIL
  - Name: Email
    URL: 'mailto:support@activemandarin.id'
    Icon-Class: fas fa-envelope
    Color: '#e17055'
    Text_Color: '#ffffff'

    # CUSTOM LINK
  #- Name: Daftar Manual
   # URL: https://docs.google.com/forms/d/e/1FAIpQLSe5TQZJePvCmKu8o38KbWLDi8RBnCgj6Nwaq4D6KhOxxhaL_w/viewform
    #Icon-Class: fas fa-link
    #Color: '#ffb142'
    #Text_Color: '#ffffff'
#contact US
  - Name: Hubungi Kami
    URL: https://api.whatsapp.com/send/?phone=6282122276775&text&type=phone_number&app_absent=0
    Icon-Class: fab fa-whatsapp
    Color: '#25d366'
    Text_Color: '#ffffff'


footer: ''

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
