# YOUR NAME OR TITLE OF YOUR SITE
name: Activemandarin course
# YOUR BRAND/PERSONAL TAGLINE
tagline: Belaajr bahasa mandarin jauh lebih mudah dengan activemandarin.id. yuk join sekarang dengan klik tombol di bawah ini

# YOUR/BRAND IMAGE URL
Image_URL: https://activemandarin.id/links/logo.jpeg

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://activemandarin.id/links/bg.jpg

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK
    
    # FACEBOOK
  - Name: Facebook
    URL: https://www.facebook.com
    Username: harsh98trivedi
    Color: '#3b5998'
    Icon-Class: fab fa-facebook

    # INSTAGRAM
  - Name: Instagram
    URL: https://www.instagram.com
    Username: harsh98trivedi
    Color: '#DD2A7B'
    Icon-Class: fab fa-instagram

    # TWITTER
 # - Name: Twitter
 #   URL: https://twitter.com
 #   Username: harsh98trivedi
 #   Color: '#1DA1F2'
  #  Icon-Class: fab fa-twitter

    # CLUBHOUSE
#  - Name: Clubhouse
#    URL: https://www.clubhouse.com
 #   Username: '@harsh98trivedi'
 #   Color: '#f1c40f'
 #   Icon-Class: fas fa-hand-paper -mt-0.5
    
    # LINKEDIN
 # - Name: LinkedIn
#    URL: https://www.linkedin.com/in
 #   Username: harsh98trivedi
  #  Color: '#2867B2'
 #   Icon-Class: fab fa-linkedin-in

    # YOUTUBE
#  - Name: YouTube
 #   URL: https://www.youtube.com/channel
 #   Username: UCS3zvA_2r1iGT7MB3NVCGAw
 #   Color: '#ff0000'
 #   Icon-Class: fab fa-youtube

    # GITHUB
#  - Name: GitHub
 #   URL: http://github.com
#    Username: harsh98trivedi
  #  Color: '#6e5494'
 #   Icon-Class: fab fa-github

    # EMAIL
  - Name: Email
    URL: 'mailto:harshtrivedi@duck.com'
    Icon-Class: fas fa-envelope
    Color: '#e17055'
    Text_Color: '#ffffff'

    # TWITCH
 # - Name: Twitch
 #   URL: 'https://twitch.tv'
 #   Username: harsh98trivedi
  #  Icon-Class: fab fa-twitch
  #  Color: '#9147fe'
  #  Text_Color: '#ffffff'

    # VIMEO
 # - Name: Vimeo
 #   URL: 'https://vimeo.com'
 #   Username: harshtrivedi
 #   Icon-Class: fab fa-vimeo-v
 #   Color: '#1ab7ea'
 #   Text_Color: '#ffffff'

    # MESSENGER
 # - Name: Messenger
  #   URL: https://m.me
  #   Username: theharshtrivedi
 #   Color: '#006AFF'
 #   Icon-Class: fab fa-facebook-messenger

    # REDDIT
  - Name: Reddit
    URL: http://reddit.com/u
    Username: harshtrivedi
    Color: '#FF4500'
    Icon-Class: fab fa-reddit-alien

  #    # TIKTOK
  # - Name: TikTok
  #   URL: https://www.tiktok.com
  #   Username: 
  #   Color: '#FE2C55'
  #   Icon-Class: fab fa-tiktok




    # CUSTOM LINK
  - Name: daftar manual
    URL: https://docs.google.com/forms/d/e/1FAIpQLSe5TQZJePvCmKu8o38KbWLDi8RBnCgj6Nwaq4D6KhOxxhaL_w/viewform
    Icon-Class: fas fa-link
    Color: '#ffb142'
    Text_Color: '#ffffff'

  - Name: hubungi kami
    URL: https://github.com/harsh98trivedi/links
    Icon-Class: fab fa-whatsapp
    Color: '#25d366'
    Text_Color: '#ffffff'

# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: ''

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
