
name: Active Mandarin course

tagline: Belajar bahasa mandarin jauh lebih mudah dengan activemandarin.id. yuk join sekarang dengan klik tombol di bawah ini


Image_URL: https://activemandarin.id/links/logo.jpeg


Cover_Image: https://activemandarin.id/links/bg.jpg

# SOCIAL MEDIA
links:  
    # INSTAGRAM
  - Name: Instagram
    URL: https://www.instagram.com
    Username: activemandarin.id
    Color: '#DD2A7B'
    Icon-Class: fab fa-instagram

    #TWITTER
  - Name: Gabung Free Trial
    URL: https://t.me/activemandarin
    Username: 
    Color: '#1DA1F2'
   Icon-Class: fab fa-telegram-plane

    # CLUBHOUSE
#  - Name: Clubhouse
#    URL: https://www.clubhouse.com
 #   Username: '@'
 #   Color: '#f1c40f'
 #   Icon-Class: fas fa-hand-paper -mt-0.5
    
    # LINKEDIN
 # - Name: LinkedIn
#    URL: https://www.linkedin.com/in
 #   Username: 
  #  Color: '#2867B2'
 #   Icon-Class: fab fa-linkedin-in

    # YOUTUBE
#  - Name: YouTube
 #   URL: https://www.youtube.com/channel
 #   Username: UCS3zvA_2r1iGT7MB3NVCGAw
 #   Color: '#ff0000'
 #   Icon-Class: fab fa-youtube

    # GITHUB
#  - Name: GitHub
 #   URL: http://github.com
#    Username: 
  #  Color: '#6e5494'
 #   Icon-Class: fab fa-github

    # EMAIL
  - Name: Email
    URL: 'mailto:support@activemandarin.id'
    Icon-Class: fas fa-envelope
    Color: '#e17055'
    Text_Color: '#ffffff'




  - Name: Tiktok
    URL: https://tiktok.com/@activemandarin
    Icon-Class: fab fa-tiktok
    Color: '#FE2C55'
    Text_Color: '#ffffff'



    # CUSTOM LINK
  - Name: daftar manual
    URL: https://docs.google.com/forms/d/e/1FAIpQLSe5TQZJePvCmKu8o38KbWLDi8RBnCgj6Nwaq4D6KhOxxhaL_w/viewform
    Icon-Class: fas fa-link
    Color: '#ffb142'
    Text_Color: '#ffffff'

  - Name: hubungi kami
    URL: https://api.whatsapp.com/send/?phone=6281368931870&text&type=phone_number&app_absent=0
    Icon-Class: fab fa-whatsapp
    Color: '#25d366'
    Text_Color: '#ffffff'

  - Name: Blog
    URL: 
    Icon-Class: fas fa-link
    Color: '#ffb142'
    Text_Color: '#ffffff'

footer: ''

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
